import type { AlertItem, Market, User } from "@/types";
import type { MarketEdge } from "@/utils/signals";

export type CampaignKind =
  | "play_hype"
  | "whale_alert"
  | "winner_spotlight"
  | "streak_milestone"
  | "market_mover"
  | "resolution"
  | "throne_taken"
  | "daily_recap"
  | "onboarding_push"
  | "fomo_blast"
  | "resolution_imminent";

export type CampaignChannel = "x" | "reddit" | "discord" | "push" | "email";

export type CampaignStatus = "drafting" | "scheduled" | "live" | "completed";

export interface CampaignMetrics {
  impressions: number;
  clicks: number;
  signups: number;
  plays: number;
  ctr: number;
}

export interface CampaignPost {
  channel: CampaignChannel;
  body: string;
  hashtags?: string[];
}

export interface Campaign {
  id: string;
  kind: CampaignKind;
  status: CampaignStatus;
  priority: number;
  headline: string;
  tagline: string;
  tone: "celebrate" | "hype" | "urgent" | "info" | "respect";
  channels: CampaignChannel[];
  posts: CampaignPost[];
  cta: { label: string; route?: string };
  marketId?: string;
  handle?: string;
  reasons: string[];
  metrics: CampaignMetrics;
  createdAt: number;
  launchedAt?: number;
  completedAt?: number;
  autoGenerated: boolean;
}

const HASH_CORE = ["#TortSite", "#MassTort", "#PredictionMarkets"];

function fmt(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return `${n}`;
}

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function emptyMetrics(): CampaignMetrics {
  return { impressions: 0, clicks: 0, signups: 0, plays: 0, ctr: 0 };
}

function stableHour(): string {
  return String(Math.floor(Date.now() / 3_600_000));
}

function stableDay(): string {
  return new Date().toDateString();
}

export function buildPlayHypeCampaign(args: {
  play: AlertItem;
  market: Market | undefined;
  edge?: MarketEdge;
}): Campaign {
  const { play, market, edge } = args;
  const caseName = market?.caseName ?? "a live tort";
  const side = play.side ?? "YES";
  const shares = play.shares ?? 0;
  const cost = play.cost ?? 0;
  const price = side === "YES" ? market?.yesPrice ?? 50 : market?.noPrice ?? 50;
  const isWhale = cost >= 10_000;

  const headline = isWhale
    ? `${play.author} loads ${fmt(cost)} pts on ${caseName}`
    : `${play.author} fires on ${caseName}`;

  const tagline = isWhale
    ? `Whale desk lit up. ${fmt(shares)} shares ${side} @ ${price}¢ — the tape is moving.`
    : `${fmt(shares)} shares ${side} @ ${price}¢. Who's riding the wave?`;

  const reasons: string[] = [];
  if (edge) {
    reasons.push(
      `Model edge ${edge.edge >= 0 ? "+" : ""}${edge.edge.toFixed(1)}¢`,
      `Confidence ${edge.confidence.toFixed(0)}%`,
    );
    if (edge.reasons[0]) reasons.push(edge.reasons[0]);
  }
  if (isWhale) reasons.push("Whale ticket");

  const posts: CampaignPost[] = [
    {
      channel: "x",
      body: `${headline}\n\n${fmt(shares)} shares ${side} @ ${price}¢ · ${fmt(cost)} pts on the line.${edge ? ` Model fair: ${edge.fairYes.toFixed(0)}¢.` : ""}\n\nFeed is live ↓`,
      hashtags: [...HASH_CORE, `#${(caseName.split(" ")[0] ?? "Tort").replace(/[^A-Za-z]/g, "")}`],
    },
    {
      channel: "reddit",
      body: `[Play Alert] ${play.author} just went ${side} on ${caseName} — ${fmt(shares)} shares @ ${price}¢ (${fmt(cost)} pts).${edge ? `\n\nTortCast model fair value sits at ${edge.fairYes.toFixed(0)}¢ YES (${edge.confidence.toFixed(0)}% confidence). ${edge.reasons.slice(0, 2).join(" · ")}.` : ""}\n\nDiscuss the docket, the Daubert, and whether this rips.`,
    },
    {
      channel: "discord",
      body: `**${headline}**\n${side} · ${fmt(shares)} sh · ${price}¢ · ${fmt(cost)} pts${isWhale ? " · 🐋 whale-tier" : ""}${edge ? `\nEdge ${edge.edge.toFixed(1)} · Conf ${edge.confidence.toFixed(0)}%` : ""}`,
    },
    {
      channel: "push",
      body: `${play.author} just took ${side} on ${caseName}. Price ${price}¢. Tap in.`,
    },
  ];

  return {
    id: `cmp-play-${play.id}`,
    kind: isWhale ? "whale_alert" : "play_hype",
    status: "drafting",
    priority: isWhale ? 92 : 70,
    headline,
    tagline,
    tone: isWhale ? "hype" : "celebrate",
    channels: isWhale ? ["x", "reddit", "discord", "push"] : ["x", "discord", "push"],
    posts,
    cta: { label: "See the market", route: market ? `/market/${market.id}` : undefined },
    marketId: market?.id,
    handle: play.author,
    reasons,
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildWinnerCampaign(args: {
  handle: string;
  caseName: string;
  marketId: string;
  points: number;
  title: string;
}): Campaign {
  const { handle, caseName, marketId, points, title } = args;
  const headline = `${handle} claims the ${title} throne`;
  const tagline = `${fmt(points)} pts banked on ${caseName}. The leaderboard just shifted.`;
  return {
    id: `cmp-winner-${marketId}-${handle.replace(/[^A-Za-z0-9]/g, "")}`,
    kind: "throne_taken",
    status: "drafting",
    priority: 88,
    headline,
    tagline,
    tone: "celebrate",
    channels: ["x", "reddit", "discord", "push", "email"],
    posts: [
      {
        channel: "x",
        body: `👑 ${headline}\n\n${caseName} · ${fmt(points)} pts\n\nThrone is defended one bellwether at a time. Who's coming for it?`,
        hashtags: [...HASH_CORE, "#Throne"],
      },
      {
        channel: "reddit",
        body: `[Leaderboard] ${handle} now holds **${title}** on ${caseName} with ${fmt(points)} points. Crown comes with docket clout and a pinned feed post.`,
      },
      {
        channel: "discord",
        body: `👑 **New throne** — ${handle} is now *${title}* (${caseName}) · ${fmt(points)} pts`,
      },
      {
        channel: "push",
        body: `${handle} just took ${title}. Can you dethrone them?`,
      },
      {
        channel: "email",
        body: `A new leader emerged on ${caseName}: ${handle} — ${fmt(points)} pts. Open Tort Market to see the full board.`,
      },
    ],
    cta: { label: "See leaderboard", route: "/(tabs)/leaderboard" },
    marketId,
    handle,
    reasons: ["Leaderboard flip", `${fmt(points)} pts`, caseName],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildStreakCampaign(args: { user: User; streak: number }): Campaign {
  const { user, streak } = args;
  return {
    id: `cmp-streak-${user.id}-${streak}`,
    kind: "streak_milestone",
    status: "drafting",
    priority: 60,
    headline: `${user.handle} hit a ${streak}-day streak`,
    tagline: `Daily discipline compounds. ${streak} days in a row, and the bonus keeps scaling.`,
    tone: "respect",
    channels: ["discord", "push"],
    posts: [
      {
        channel: "discord",
        body: `🔥 ${user.handle} is on a ${streak}-day claim streak. Bonus multiplier active.`,
      },
      {
        channel: "push",
        body: `Day ${streak} streak locked. Keep it going tomorrow for the next tier.`,
      },
    ],
    cta: { label: "Claim tomorrow", route: "/(tabs)" },
    handle: user.handle,
    reasons: [`${streak}-day streak`, "Retention signal"],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildMarketMoverCampaign(args: { market: Market; edge?: MarketEdge }): Campaign {
  const { market, edge } = args;
  const up = market.change24h >= 0;
  const headline = `${market.caseName} ${up ? "ripped" : "dropped"} ${Math.abs(market.change24h).toFixed(1)}% in 24h`;
  return {
    id: `cmp-mover-${market.id}-${stableHour()}`,
    kind: "market_mover",
    status: "drafting",
    priority: 72,
    headline,
    tagline: `${market.defendant} · YES now ${market.yesPrice}¢.${edge ? ` Model fair ${edge.fairYes.toFixed(0)}¢ · ${edge.recommendedSide} edge.` : ""}`,
    tone: up ? "hype" : "urgent",
    channels: ["x", "reddit", "discord", "push"],
    posts: [
      {
        channel: "x",
        body: `${headline}\n\nYES ${market.yesPrice}¢ · NO ${market.noPrice}¢${edge ? ` · fair ${edge.fairYes.toFixed(0)}¢ (${edge.confidence.toFixed(0)}% conf)` : ""}.\n\nDocket's talking.`,
        hashtags: [...HASH_CORE, `#${(market.defendant.split(" ")[0] ?? "Tort").replace(/[^A-Za-z]/g, "")}`],
      },
      {
        channel: "reddit",
        body: `${market.caseName} moved ${market.change24h >= 0 ? "+" : ""}${market.change24h.toFixed(1)}% on the day. What signal is the crowd pricing in?`,
      },
      {
        channel: "discord",
        body: `📈 ${market.caseName}: ${market.change24h >= 0 ? "+" : ""}${market.change24h.toFixed(1)}% · YES ${market.yesPrice}¢`,
      },
      {
        channel: "push",
        body: `${market.caseName} just moved ${Math.abs(market.change24h).toFixed(1)}%. Check the tape.`,
      },
    ],
    cta: { label: "Open market", route: `/market/${market.id}` },
    marketId: market.id,
    reasons: edge ? edge.reasons.slice(0, 3) : [`${market.change24h.toFixed(1)}% 24h`],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildDailyRecapCampaign(args: {
  topPlay?: AlertItem;
  topMarket?: Market;
  totalPlays: number;
}): Campaign {
  const { topPlay, topMarket, totalPlays } = args;
  const headline = `Tort Market daily recap · ${totalPlays} plays on the tape`;
  const tagline = topMarket
    ? `${topMarket.caseName} led the board at YES ${topMarket.yesPrice}¢.${topPlay ? ` ${topPlay.author} took the biggest swing.` : ""}`
    : `Another full session in the books.`;
  return {
    id: `cmp-recap-${stableDay()}`,
    kind: "daily_recap",
    status: "drafting",
    priority: 40,
    headline,
    tagline,
    tone: "info",
    channels: ["email", "reddit", "discord"],
    posts: [
      {
        channel: "email",
        body: `${headline}\n\n${tagline}\n\nLog back in to review your book, claim your daily points, and check tomorrow's top edges.`,
      },
      {
        channel: "reddit",
        body: `Daily wrap — ${totalPlays} plays routed through Tort Market today.${topMarket ? ` Mover of the day: ${topMarket.caseName}.` : ""}`,
      },
      {
        channel: "discord",
        body: `📊 Daily recap — ${totalPlays} plays${topMarket ? ` · Mover: ${topMarket.caseName}` : ""}${topPlay ? ` · Biggest swing: ${topPlay.author}` : ""}`,
      },
    ],
    cta: { label: "Open app", route: "/(tabs)" },
    marketId: topMarket?.id,
    reasons: [`${totalPlays} plays`, "Daily retention"],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildOnboardingCampaign(handle: string): Campaign {
  const cleanHandle = handle.replace(/[^A-Za-z0-9]/g, "");
  return {
    id: `cmp-welcome-${cleanHandle}`,
    kind: "onboarding_push",
    status: "drafting",
    priority: 55,
    headline: `${handle} joined the POC`,
    tagline: `25,000 welcome points dropped. First play teed up in the coach.`,
    tone: "celebrate",
    channels: ["discord", "push", "email"],
    posts: [
      {
        channel: "discord",
        body: `🪪 New member · ${handle} · welcome-bonus armed`,
      },
      {
        channel: "push",
        body: `Welcome, ${handle}. Your first edge is waiting in the coach.`,
      },
      {
        channel: "email",
        body: `Welcome to the Tort Market POC, ${handle}. Your 25,000 starter points are live. Claim, place your first play, and we'll guide the rest.`,
      },
    ],
    cta: { label: "Open coach", route: "/(tabs)/coach" },
    handle,
    reasons: ["New signup", "Activation window"],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildFOMOCampaign(args: {
  market: Market;
  edge?: MarketEdge;
  recentPlays: number;
}): Campaign {
  const { market, edge, recentPlays } = args;
  const headline = `${recentPlays} traders just positioned on ${market.caseName}`;
  const tagline = `Volume spike detected. YES at ${market.yesPrice}¢. The crowd is pricing in movement.`;
  return {
    id: `cmp-fomo-${market.id}-${stableHour()}`,
    kind: "fomo_blast",
    status: "drafting",
    priority: 82,
    headline,
    tagline,
    tone: "hype",
    channels: ["x", "discord", "push"],
    posts: [
      {
        channel: "x",
        body: `${recentPlays} traders just moved on ${market.caseName} in the last hour.\n\nYES ${market.yesPrice}¢${edge ? ` · model fair ${edge.fairYes.toFixed(0)}¢ · edge ${edge.edge >= 0 ? "+" : ""}${edge.edge.toFixed(1)}` : ""}.\n\nYou still have time. Maybe.`,
        hashtags: [...HASH_CORE, `#${(market.caseName.split(" ")[0] ?? "Tort").replace(/[^A-Za-z]/g, "")}`],
      },
      {
        channel: "discord",
        body: `🔔 Volume spike — ${market.caseName} · ${recentPlays} plays this hour · YES ${market.yesPrice}¢${edge ? ` · conf ${edge.confidence.toFixed(0)}%` : ""}`,
      },
      {
        channel: "push",
        body: `${recentPlays} traders just piled into ${market.caseName}. Are you in?`,
      },
    ],
    cta: { label: "See market", route: `/market/${market.id}` },
    marketId: market.id,
    reasons: [`${recentPlays} recent plays`, "Volume spike", edge?.reasons[0] ?? ""],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function buildResolutionImminentCampaign(args: {
  market: Market;
  edge?: MarketEdge;
}): Campaign {
  const { market, edge } = args;
  const up = market.change24h >= 0;
  const headline = `Resolution signal: ${market.caseName}`;
  const tagline = `${up ? "+" : ""}${market.change24h.toFixed(1)}% in 24h. Fast price moves precede verdicts.`;
  return {
    id: `cmp-resolution-${market.id}-${stableDay()}`,
    kind: "resolution_imminent",
    status: "drafting",
    priority: 85,
    headline,
    tagline,
    tone: "urgent",
    channels: ["x", "reddit", "discord", "push", "email"],
    posts: [
      {
        channel: "x",
        body: `⚖️ ${headline}\n\nYES ${market.yesPrice}¢ · ${up ? "+" : ""}${market.change24h.toFixed(1)}% today${edge ? ` · model says ${edge.recommendedSide} @ ${edge.fairYes.toFixed(0)}¢ fair` : ""}.\n\nClock might be ticking.`,
        hashtags: [...HASH_CORE, `#${(market.caseName.split(" ")[0] ?? "Tort").replace(/[^A-Za-z]/g, "")}`, "#Verdict"],
      },
      {
        channel: "reddit",
        body: `${market.caseName} is moving fast — ${up ? "+" : ""}${market.change24h.toFixed(1)}% in 24h. Historical pattern: sharp pre-verdict moves. MDL sentiment: ${market.mdlSentiment}/100. Daubert: ${market.daubertStrength}/100. Last chance to position before the ruling?`,
      },
      {
        channel: "discord",
        body: `⚖️ **Resolution watch** — ${market.caseName} · ${up ? "+" : ""}${market.change24h.toFixed(1)}% 24h · YES ${market.yesPrice}¢`,
      },
      {
        channel: "push",
        body: `${market.caseName} is moving fast. Verdict signal or fake-out? Check the model.`,
      },
      {
        channel: "email",
        body: `${headline}\n\n${tagline} MDL sentiment: ${market.mdlSentiment}/100. Daubert strength: ${market.daubertStrength}/100.\n\nPosition now or watch from the sidelines.`,
      },
    ],
    cta: { label: "Open market", route: `/market/${market.id}` },
    marketId: market.id,
    reasons: [`${market.change24h.toFixed(1)}% 24h`, "Verdict signal", edge?.reasons[0] ?? ""],
    metrics: emptyMetrics(),
    createdAt: Date.now(),
    autoGenerated: true,
  };
}

export function simulateReach(campaign: Campaign, _elapsedMs: number): CampaignMetrics {
  const launched = campaign.launchedAt ?? campaign.createdAt;
  const ageMin = Math.max(0, (Date.now() - launched) / 60_000);
  const curve = 1 - Math.exp(-ageMin / 45);
  const channelMultiplier = campaign.channels.length;
  const base = campaign.priority * 90 + campaign.channels.length * 320;
  const viralCoefficient = campaign.kind === "whale_alert" ? 1.6 :
    campaign.kind === "throne_taken" ? 1.4 :
    campaign.kind === "resolution_imminent" ? 1.5 :
    campaign.kind === "fomo_blast" ? 1.3 : 1.0;
  const target = base * channelMultiplier * (0.8 + Math.random() * 0.5) * viralCoefficient;
  const impressions = Math.round(target * curve);
  const ctr =
    0.018 + Math.random() * 0.04 +
    (campaign.tone === "hype" ? 0.015 : 0) +
    (campaign.tone === "urgent" ? 0.012 : 0) +
    (campaign.kind === "fomo_blast" ? 0.02 : 0);
  const clicks = Math.round(impressions * ctr);
  const signupRate = campaign.kind === "onboarding_push" ? 0.22 :
    campaign.kind === "fomo_blast" ? 0.10 :
    campaign.kind === "resolution_imminent" ? 0.08 : 0.06;
  const signups = Math.round(clicks * signupRate);
  const plays = Math.round(clicks * 0.14);
  return {
    impressions,
    clicks,
    signups,
    plays,
    ctr: Number((ctr * 100).toFixed(2)),
  };
}

export function channelLabel(c: CampaignChannel): string {
  return { x: "X", reddit: "Reddit", discord: "Discord", push: "Push", email: "Email" }[c];
}

export function kindLabel(k: CampaignKind): string {
  return {
    play_hype: "Play Hype",
    whale_alert: "Whale Alert",
    winner_spotlight: "Winner Spotlight",
    streak_milestone: "Streak Milestone",
    market_mover: "Market Mover",
    resolution: "Resolution",
    throne_taken: "Throne Taken",
    daily_recap: "Daily Recap",
    onboarding_push: "Onboarding Push",
    fomo_blast: "FOMO Blast",
    resolution_imminent: "Resolution Watch",
  }[k];
}

export function toneColor(tone: Campaign["tone"]): string {
  return {
    celebrate: "#10B981",
    hype: "#FF6A1A",
    urgent: "#EF4444",
    info: "#2563EB",
    respect: "#7C3AED",
  }[tone];
}

export { pick };
